//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ML.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ML.Languages.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account has been locked.
        /// </summary>
        public static string AccountHasBeenLocked {
            get {
                return ResourceManager.GetString("AccountHasBeenLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not exist.
        /// </summary>
        public static string AccountIsNotExist {
            get {
                return ResourceManager.GetString("AccountIsNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation parameters.
        /// </summary>
        public static string ActivationParameters {
            get {
                return ResourceManager.GetString("ActivationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ActivedFailed {
            get {
                return ResourceManager.GetString("ActivedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active success.
        /// </summary>
        public static string ActivedSuccess {
            get {
                return ResourceManager.GetString("ActivedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency.
        /// </summary>
        public static string AgencyLevel1 {
            get {
                return ResourceManager.GetString("AgencyLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ANTENNA.
        /// </summary>
        public static string Antenna {
            get {
                return ResourceManager.GetString("Antenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antenna ID.
        /// </summary>
        public static string AntennaID {
            get {
                return ResourceManager.GetString("AntennaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto connections.
        /// </summary>
        public static string AutoConnections {
            get {
                return ResourceManager.GetString("AutoConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto reading.
        /// </summary>
        public static string AutoReading {
            get {
                return ResourceManager.GetString("AutoReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Notify.
        /// </summary>
        public static string BackupNotify {
            get {
                return ResourceManager.GetString("BackupNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic Setting.
        /// </summary>
        public static string BasicSetting {
            get {
                return ResourceManager.GetString("BasicSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baud rate.
        /// </summary>
        public static string BaudRate {
            get {
                return ResourceManager.GetString("BaudRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brust (External).
        /// </summary>
        public static string BrustExternal {
            get {
                return ResourceManager.GetString("BrustExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be null.
        /// </summary>
        public static string CannotBeNull {
            get {
                return ResourceManager.GetString("CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot close applications.
        /// </summary>
        public static string CannotCloseApplications {
            get {
                return ResourceManager.GetString("CannotCloseApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start RFID devices.
        /// </summary>
        public static string CannotStartRFIDDevices {
            get {
                return ResourceManager.GetString("CannotStartRFIDDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check data.
        /// </summary>
        public static string CheckData {
            get {
                return ResourceManager.GetString("CheckData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked failed.
        /// </summary>
        public static string CheckedFailed {
            get {
                return ResourceManager.GetString("CheckedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check success.
        /// </summary>
        public static string CheckedSuccess {
            get {
                return ResourceManager.GetString("CheckedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Pallet.
        /// </summary>
        public static string CheckPallet {
            get {
                return ResourceManager.GetString("CheckPallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChipID.
        /// </summary>
        public static string ChipID {
            get {
                return ResourceManager.GetString("ChipID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a folder.
        /// </summary>
        public static string ChooseAFolder {
            get {
                return ResourceManager.GetString("ChooseAFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearlog.
        /// </summary>
        public static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear logs.
        /// </summary>
        public static string ClearLogs {
            get {
                return ResourceManager.GetString("ClearLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close applications.
        /// </summary>
        public static string CloseApplications {
            get {
                return ResourceManager.GetString("CloseApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code count.
        /// </summary>
        public static string CodeCount {
            get {
                return ResourceManager.GetString("CodeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command.
        /// </summary>
        public static string Command {
            get {
                return ResourceManager.GetString("Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM port.
        /// </summary>
        public static string COMPort {
            get {
                return ResourceManager.GetString("COMPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection failed.
        /// </summary>
        public static string ConnectionFailed {
            get {
                return ResourceManager.GetString("ConnectionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to PLC.
        /// </summary>
        public static string ConnectToPLC {
            get {
                return ResourceManager.GetString("ConnectToPLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to RFID.
        /// </summary>
        public static string ConnectToRFID {
            get {
                return ResourceManager.GetString("ConnectToRFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string Control {
            get {
                return ResourceManager.GetString("Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creat folder failed.
        /// </summary>
        public static string CreatFolderFailed {
            get {
                return ResourceManager.GetString("CreatFolderFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data bit.
        /// </summary>
        public static string DataBit {
            get {
                return ResourceManager.GetString("DataBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data scanned results.
        /// </summary>
        public static string DataScannedResults {
            get {
                return ResourceManager.GetString("DataScannedResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of expiry.
        /// </summary>
        public static string DateOfExpiry {
            get {
                return ResourceManager.GetString("DateOfExpiry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of manufacture.
        /// </summary>
        public static string DateOfManufacture {
            get {
                return ResourceManager.GetString("DateOfManufacture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decode Time.
        /// </summary>
        public static string DecodeTime {
            get {
                return ResourceManager.GetString("DecodeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DelayTime (ms).
        /// </summary>
        public static string DelayTimeMs {
            get {
                return ResourceManager.GetString("DelayTimeMs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Trigger time.
        /// </summary>
        public static string DelayTriggerTime {
            get {
                return ResourceManager.GetString("DelayTriggerTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay Type.
        /// </summary>
        public static string DelayType {
            get {
                return ResourceManager.GetString("DelayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete logs.
        /// </summary>
        public static string DeleteLogs {
            get {
                return ResourceManager.GetString("DeleteLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery bill.
        /// </summary>
        public static string DeliveryBill {
            get {
                return ResourceManager.GetString("DeliveryBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery ID.
        /// </summary>
        public static string DeliveryID {
            get {
                return ResourceManager.GetString("DeliveryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device address.
        /// </summary>
        public static string DeviceAddress {
            get {
                return ResourceManager.GetString("DeviceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution code.
        /// </summary>
        public static string DistributionCode {
            get {
                return ResourceManager.GetString("DistributionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribution schedules.
        /// </summary>
        public static string DistributionSchedules {
            get {
                return ResourceManager.GetString("DistributionSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate code.
        /// </summary>
        public static string DuplicateCode {
            get {
                return ResourceManager.GetString("DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Filter.
        /// </summary>
        public static string EnableFilter {
            get {
                return ResourceManager.GetString("EnableFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors.
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        public static string Event {
            get {
                return ResourceManager.GetString("Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File data.
        /// </summary>
        public static string FileData {
            get {
                return ResourceManager.GetString("FileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Data.
        /// </summary>
        public static string FilterData {
            get {
                return ResourceManager.GetString("FilterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder doesn&apos;t exist.
        /// </summary>
        public static string FolderDoseNotExist {
            get {
                return ResourceManager.GetString("FolderDoseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General info.
        /// </summary>
        public static string GeneralInfo {
            get {
                return ResourceManager.GetString("GeneralInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPI Enable.
        /// </summary>
        public static string GPIEnable {
            get {
                return ResourceManager.GetString("GPIEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPIO.
        /// </summary>
        public static string GPIO {
            get {
                return ResourceManager.GetString("GPIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPI Params.
        /// </summary>
        public static string GPIParams {
            get {
                return ResourceManager.GetString("GPIParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPI with Timeout.
        /// </summary>
        public static string GPIwithTimeout {
            get {
                return ResourceManager.GetString("GPIwithTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPO States.
        /// </summary>
        public static string GPOStates {
            get {
                return ResourceManager.GetString("GPOStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to H-&gt;L.
        /// </summary>
        public static string HL {
            get {
                return ResourceManager.GetString("HL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host name.
        /// </summary>
        public static string HostName {
            get {
                return ResourceManager.GetString("HostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        public static string Informations {
            get {
                return ResourceManager.GetString("Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string Job {
            get {
                return ResourceManager.GetString("Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key information.
        /// </summary>
        public static string KeyInformation {
            get {
                return ResourceManager.GetString("KeyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword.
        /// </summary>
        public static string KeyWord {
            get {
                return ResourceManager.GetString("KeyWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L-&gt;H.
        /// </summary>
        public static string LH {
            get {
                return ResourceManager.GetString("LH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link server.
        /// </summary>
        public static string LinkServer {
            get {
                return ResourceManager.GetString("LinkServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log details.
        /// </summary>
        public static string LogDetails {
            get {
                return ResourceManager.GetString("LogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login account.
        /// </summary>
        public static string LoginAccount {
            get {
                return ResourceManager.GetString("LoginAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOT No.
        /// </summary>
        public static string LOTNo {
            get {
                return ResourceManager.GetString("LOTNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual reading.
        /// </summary>
        public static string ManualReading {
            get {
                return ResourceManager.GetString("ManualReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Size Memory Bank.
        /// </summary>
        public static string MaxSizeMemoryBank {
            get {
                return ResourceManager.GetString("MaxSizeMemoryBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Tag Count.
        /// </summary>
        public static string MaxTagCount {
            get {
                return ResourceManager.GetString("MaxTagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Tag ID Length.
        /// </summary>
        public static string MaxTagIDLength {
            get {
                return ResourceManager.GetString("MaxTagIDLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Connection.
        /// </summary>
        public static string MgsConnection {
            get {
                return ResourceManager.GetString("MgsConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss pallet.
        /// </summary>
        public static string MissPallet {
            get {
                return ResourceManager.GetString("MissPallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miss product.
        /// </summary>
        public static string MissProduct {
            get {
                return ResourceManager.GetString("MissProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to close applications?.
        /// </summary>
        public static string MsgAreYouSureToCloseApplications {
            get {
                return ResourceManager.GetString("MsgAreYouSureToCloseApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to confirm the deliry bill.
        /// </summary>
        public static string MsgAreYouSureToConfirmTheDeliryBill {
            get {
                return ResourceManager.GetString("MsgAreYouSureToConfirmTheDeliryBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete the delivery bill logs?.
        /// </summary>
        public static string MsgAreYouSureToDeleteTheDeliveryBillLogs {
            get {
                return ResourceManager.GetString("MsgAreYouSureToDeleteTheDeliveryBillLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup parameter successfully!.
        /// </summary>
        public static string MsgBackupParameterSuccessfully {
            get {
                return ResourceManager.GetString("MsgBackupParameterSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup parameter unsuccessfully!.
        /// </summary>
        public static string MsgBackupParameterUnsuccessfully {
            get {
                return ResourceManager.GetString("MsgBackupParameterUnsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm delivery bill.
        /// </summary>
        public static string MsgConfirmDeliveryBill {
            get {
                return ResourceManager.GetString("MsgConfirmDeliveryBill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have database.
        /// </summary>
        public static string MsgDontHaveDatabase {
            get {
                return ResourceManager.GetString("MsgDontHaveDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        public static string MsgDoYouWantToContinue {
            get {
                return ResourceManager.GetString("MsgDoYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to stop this process?.
        /// </summary>
        public static string MsgDoYouWantToStopThisProcess {
            get {
                return ResourceManager.GetString("MsgDoYouWantToStopThisProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail Format.
        /// </summary>
        public static string MsgFailFormat {
            get {
                return ResourceManager.GetString("MsgFailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product in Pallet.
        /// </summary>
        public static string MsgNoProductInPallet {
            get {
                return ResourceManager.GetString("MsgNoProductInPallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet excess quantity.
        /// </summary>
        public static string MsgPalletExcessQuantity {
            get {
                return ResourceManager.GetString("MsgPalletExcessQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet have multiple values.
        /// </summary>
        public static string MsgPalletHaveMultipleValues {
            get {
                return ResourceManager.GetString("MsgPalletHaveMultipleValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet lack quantity.
        /// </summary>
        public static string MsgPalletLackQuantity {
            get {
                return ResourceManager.GetString("MsgPalletLackQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet no scan code result data.
        /// </summary>
        public static string MsgPalletNoScanCodeResultData {
            get {
                return ResourceManager.GetString("MsgPalletNoScanCodeResultData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet sufficient quantity.
        /// </summary>
        public static string MsgPalletSufficientQuantity {
            get {
                return ResourceManager.GetString("MsgPalletSufficientQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect.
        /// </summary>
        public static string MsgPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("MsgPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password not match.
        /// </summary>
        public static string MsgPasswordNotMatch {
            get {
                return ResourceManager.GetString("MsgPasswordNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your systems.
        /// </summary>
        public static string MsgPleaseCheckYourSystems {
            get {
                return ResourceManager.GetString("MsgPleaseCheckYourSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm this information.
        /// </summary>
        public static string MsgPleaseConfirmThisInformation {
            get {
                return ResourceManager.GetString("MsgPleaseConfirmThisInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect with PLC.
        /// </summary>
        public static string MsgPleaseConnectWithPLC {
            get {
                return ResourceManager.GetString("MsgPleaseConnectWithPLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please connect with RFID.
        /// </summary>
        public static string MsgPleaseConnectWithRFID {
            get {
                return ResourceManager.GetString("MsgPleaseConnectWithRFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string MsgPleaseWait {
            get {
                return ResourceManager.GetString("MsgPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product distributions Model.
        /// </summary>
        public static string MsgProductDistributionsModule {
            get {
                return ResourceManager.GetString("MsgProductDistributionsModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production-Bagging-Warehousing Model.
        /// </summary>
        public static string MsgProductionBaggingWarehousingModule {
            get {
                return ResourceManager.GetString("MsgProductionBaggingWarehousingModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product is defective.
        /// </summary>
        public static string MsgProductIsDefective {
            get {
                return ResourceManager.GetString("MsgProductIsDefective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore  parameter successfully!.
        /// </summary>
        public static string MsgRestoreParameterSuccessfully {
            get {
                return ResourceManager.GetString("MsgRestoreParameterSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore  parameter unsuccessfully!.
        /// </summary>
        public static string MsgRestoreParameterUnsuccessfully {
            get {
                return ResourceManager.GetString("MsgRestoreParameterUnsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Setting Successfully..
        /// </summary>
        public static string MsgRFIDSettingSuccessfully {
            get {
                return ResourceManager.GetString("MsgRFIDSettingSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID Setting Unsuccessfully..
        /// </summary>
        public static string MsgRFIDSettingUnsuccessfully {
            get {
                return ResourceManager.GetString("MsgRFIDSettingUnsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting Notification.
        /// </summary>
        public static string MsgSettingNotification {
            get {
                return ResourceManager.GetString("MsgSettingNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The delivery bill is confirm.
        /// </summary>
        public static string MsgTheDeliveryBillIsConfirm {
            get {
                return ResourceManager.GetString("MsgTheDeliveryBillIsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be {0} to {1}.
        /// </summary>
        public static string MsgValueMustBe {
            get {
                return ResourceManager.GetString("MsgValueMustBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Validate.
        /// </summary>
        public static string MsgValueValidate {
            get {
                return ResourceManager.GetString("MsgValueValidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be greater than 0.
        /// </summary>
        public static string MustBeGreaterThan0 {
            get {
                return ResourceManager.GetString("MustBeGreaterThan0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No product in pallet.
        /// </summary>
        public static string NoProductInPallet {
            get {
                return ResourceManager.GetString("NoProductInPallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No response from server.
        /// </summary>
        public static string NoResponseFromServer {
            get {
                return ResourceManager.GetString("NoResponseFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        public static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not match.
        /// </summary>
        public static string NotMatch {
            get {
                return ResourceManager.GetString("NotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null delivery ID.
        /// </summary>
        public static string NullDeliveryID {
            get {
                return ResourceManager.GetString("NullDeliveryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator.
        /// </summary>
        public static string Operator {
            get {
                return ResourceManager.GetString("Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered.
        /// </summary>
        public static string Ordered {
            get {
                return ResourceManager.GetString("Ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered total.
        /// </summary>
        public static string OrderedTotal {
            get {
                return ResourceManager.GetString("OrderedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet code.
        /// </summary>
        public static string PalletCode {
            get {
                return ResourceManager.GetString("PalletCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parity.
        /// </summary>
        public static string Parity {
            get {
                return ResourceManager.GetString("Parity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords does not match.
        /// </summary>
        public static string PasswordsDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission.
        /// </summary>
        public static string Permission {
            get {
                return ResourceManager.GetString("Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping.
        /// </summary>
        public static string Ping {
            get {
                return ResourceManager.GetString("Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping result.
        /// </summary>
        public static string PingResult {
            get {
                return ResourceManager.GetString("PingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLC.
        /// </summary>
        public static string PLC {
            get {
                return ResourceManager.GetString("PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check IP and port of devices.
        /// </summary>
        public static string PleaseCheckIPAndPortOfDevices {
            get {
                return ResourceManager.GetString("PleaseCheckIPAndPortOfDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your data.
        /// </summary>
        public static string PleaseCheckYourData {
            get {
                return ResourceManager.GetString("PleaseCheckYourData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your server.
        /// </summary>
        public static string PleaseCheckYourServer {
            get {
                return ResourceManager.GetString("PleaseCheckYourServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your systems.
        /// </summary>
        public static string PleaseCheckYourSystems {
            get {
                return ResourceManager.GetString("PleaseCheckYourSystems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact administrator to unlock.
        /// </summary>
        public static string PleaseContactAdministratorToUnlock {
            get {
                return ResourceManager.GetString("PleaseContactAdministratorToUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the files to preview.
        /// </summary>
        public static string PleaseSelectTheFilesToPreview {
            get {
                return ResourceManager.GetString("PleaseSelectTheFilesToPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again.
        /// </summary>
        public static string PleaseTryAgain {
            get {
                return ResourceManager.GetString("PleaseTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please stop trigger before closed.
        /// </summary>
        public static string PleasetStopTriggerBeforeClose {
            get {
                return ResourceManager.GetString("PleasetStopTriggerBeforeClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product code.
        /// </summary>
        public static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product delivery offline.
        /// </summary>
        public static string ProductDeliveryOffline {
            get {
                return ResourceManager.GetString("ProductDeliveryOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product delivery online.
        /// </summary>
        public static string ProductDeliveryOnline {
            get {
                return ResourceManager.GetString("ProductDeliveryOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product details.
        /// </summary>
        public static string ProductDetails {
            get {
                return ResourceManager.GetString("ProductDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product import offline.
        /// </summary>
        public static string ProductImportOffline {
            get {
                return ResourceManager.GetString("ProductImportOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product import online.
        /// </summary>
        public static string ProductImportOnline {
            get {
                return ResourceManager.GetString("ProductImportOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production name.
        /// </summary>
        public static string ProductionName {
            get {
                return ResourceManager.GetString("ProductionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity to export.
        /// </summary>
        public static string QuantityToExport {
            get {
                return ResourceManager.GetString("QuantityToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity to import.
        /// </summary>
        public static string QuantityToImport {
            get {
                return ResourceManager.GetString("QuantityToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading.
        /// </summary>
        public static string Reading {
            get {
                return ResourceManager.GetString("Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read RFID.
        /// </summary>
        public static string ReadRFID {
            get {
                return ResourceManager.GetString("ReadRFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot.
        /// </summary>
        public static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot Device.
        /// </summary>
        public static string RebootDevice {
            get {
                return ResourceManager.GetString("RebootDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release note.
        /// </summary>
        public static string ReleaseNote {
            get {
                return ResourceManager.GetString("ReleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember login.
        /// </summary>
        public static string RememberLogin {
            get {
                return ResourceManager.GetString("RememberLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Device.
        /// </summary>
        public static string ResetDevice {
            get {
                return ResourceManager.GetString("ResetDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response from server.
        /// </summary>
        public static string ResponseFromServer {
            get {
                return ResourceManager.GetString("ResponseFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        public static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Notify.
        /// </summary>
        public static string RestoreNotify {
            get {
                return ResourceManager.GetString("RestoreNotify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type password.
        /// </summary>
        public static string RetypePassword {
            get {
                return ResourceManager.GetString("RetypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID.
        /// </summary>
        public static string RFID {
            get {
                return ResourceManager.GetString("RFID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RFID settings.
        /// </summary>
        public static string RFIDSettings {
            get {
                return ResourceManager.GetString("RFIDSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows count.
        /// </summary>
        public static string RowsCount {
            get {
                return ResourceManager.GetString("RowsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSSI.
        /// </summary>
        public static string RSSI {
            get {
                return ResourceManager.GetString("RSSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveDataLocations.
        /// </summary>
        public static string SaveDataLocations {
            get {
                return ResourceManager.GetString("SaveDataLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan data.
        /// </summary>
        public static string ScanData {
            get {
                return ResourceManager.GetString("ScanData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan datetime.
        /// </summary>
        public static string ScanDatetime {
            get {
                return ResourceManager.GetString("ScanDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan failed.
        /// </summary>
        public static string ScanFailed {
            get {
                return ResourceManager.GetString("ScanFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QRCode.
        /// </summary>
        public static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan success.
        /// </summary>
        public static string ScanSuccess {
            get {
                return ResourceManager.GetString("ScanSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules&apos;s files dose not exist.
        /// </summary>
        public static string SchedulesFilesDoseNotExist {
            get {
                return ResourceManager.GetString("SchedulesFilesDoseNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedules info.
        /// </summary>
        public static string SchedulesInfo {
            get {
                return ResourceManager.GetString("SchedulesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máy chủ.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server activation.
        /// </summary>
        public static string ServerActivation {
            get {
                return ResourceManager.GetString("ServerActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not response.
        /// </summary>
        public static string ServerIsNotResponse {
            get {
                return ResourceManager.GetString("ServerIsNotResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server reponse.
        /// </summary>
        public static string ServerReponse {
            get {
                return ResourceManager.GetString("ServerReponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server status.
        /// </summary>
        public static string ServerStatus {
            get {
                return ResourceManager.GetString("ServerStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting For DM60X Camera.
        /// </summary>
        public static string SettingForDM60XCamera {
            get {
                return ResourceManager.GetString("SettingForDM60XCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single (External).
        /// </summary>
        public static string SingleExternal {
            get {
                return ResourceManager.GetString("SingleExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting.
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Trigger.
        /// </summary>
        public static string StartTrigger {
            get {
                return ResourceManager.GetString("StartTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop bit.
        /// </summary>
        public static string StopBit {
            get {
                return ResourceManager.GetString("StopBit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stoped.
        /// </summary>
        public static string Stoped {
            get {
                return ResourceManager.GetString("Stoped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Trigger.
        /// </summary>
        public static string StopTrigger {
            get {
                return ResourceManager.GetString("StopTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subnet Mask.
        /// </summary>
        public static string SubnetMask {
            get {
                return ResourceManager.GetString("SubnetMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol Read.
        /// </summary>
        public static string SymbolRead {
            get {
                return ResourceManager.GetString("SymbolRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string Sync {
            get {
                return ResourceManager.GetString("Sync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync data.
        /// </summary>
        public static string SyncData {
            get {
                return ResourceManager.GetString("SyncData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync data with server.
        /// </summary>
        public static string SyncDataWithServer {
            get {
                return ResourceManager.GetString("SyncDataWithServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync schedules.
        /// </summary>
        public static string SyncSchedules {
            get {
                return ResourceManager.GetString("SyncSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System settings.
        /// </summary>
        public static string SystemSettings {
            get {
                return ResourceManager.GetString("SystemSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag ID.
        /// </summary>
        public static string TagID {
            get {
                return ResourceManager.GetString("TagID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Report Trigger.
        /// </summary>
        public static string TagReportTrigger {
            get {
                return ResourceManager.GetString("TagReportTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAG STORAGE.
        /// </summary>
        public static string TAGSTORAGE {
            get {
                return ResourceManager.GetString("TAGSTORAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The applications must be restart to complete.
        /// </summary>
        public static string TheApplicationsMustBeRestartToComplete {
            get {
                return ResourceManager.GetString("TheApplicationsMustBeRestartToComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The applications will be restart.
        /// </summary>
        public static string TheApplicationsWillBeRestart {
            get {
                return ResourceManager.GetString("TheApplicationsWillBeRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation completed successfully.
        /// </summary>
        public static string TheOperationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("TheOperationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system has stopped.
        /// </summary>
        public static string TheSystemHasStopped {
            get {
                return ResourceManager.GetString("TheSystemHasStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} are running.
        /// </summary>
        public static string TheXAreRunning {
            get {
                return ResourceManager.GetString("TheXAreRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout.
        /// </summary>
        public static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total export.
        /// </summary>
        public static string TotalExport {
            get {
                return ResourceManager.GetString("TotalExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total tag count.
        /// </summary>
        public static string TotalTagCount {
            get {
                return ResourceManager.GetString("TotalTagCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmit Power (100*dBm).
        /// </summary>
        public static string TransmitPower {
            get {
                return ResourceManager.GetString("TransmitPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        public static string Trigger {
            get {
                return ResourceManager.GetString("Trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIGGERS.
        /// </summary>
        public static string TRIGGERS {
            get {
                return ResourceManager.GetString("TRIGGERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Setting.
        /// </summary>
        public static string TriggerSetting {
            get {
                return ResourceManager.GetString("TriggerSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger Type.
        /// </summary>
        public static string TriggerType {
            get {
                return ResourceManager.GetString("TriggerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown pallet.
        /// </summary>
        public static string UnknownPallet {
            get {
                return ResourceManager.GetString("UnknownPallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Static IP Address.
        /// </summary>
        public static string UseStaticIPAddress {
            get {
                return ResourceManager.GetString("UseStaticIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewlog.
        /// </summary>
        public static string ViewLog {
            get {
                return ResourceManager.GetString("ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting.
        /// </summary>
        public static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait to sync.
        /// </summary>
        public static string WaitToSync {
            get {
                return ResourceManager.GetString("WaitToSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web browser.
        /// </summary>
        public static string WebBrowser {
            get {
                return ResourceManager.GetString("WebBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong ID code.
        /// </summary>
        public static string WrongIDCode {
            get {
                return ResourceManager.GetString("WrongIDCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong pallet.
        /// </summary>
        public static string WrongPallet {
            get {
                return ResourceManager.GetString("WrongPallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong product code.
        /// </summary>
        public static string WrongProductCode {
            get {
                return ResourceManager.GetString("WrongProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong product name.
        /// </summary>
        public static string WrongProductName {
            get {
                return ResourceManager.GetString("WrongProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong schedules&apos;s files.
        /// </summary>
        public static string WrongSchedulesFiles {
            get {
                return ResourceManager.GetString("WrongSchedulesFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have completed the quantity to be distributed.
        /// </summary>
        public static string YouHaveCompletedTheQuantityToBeDistributed {
            get {
                return ResourceManager.GetString("YouHaveCompletedTheQuantityToBeDistributed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have some TIMEOUT issue.
        /// </summary>
        public static string YouHaveSomeTIMEOUTIssue {
            get {
                return ResourceManager.GetString("YouHaveSomeTIMEOUTIssue", resourceCulture);
            }
        }
    }
}
